### ISSUE TITLE
wasm-bpf.md has broken image links

### ISSUE THREAD

**Issue by evensolberg** [eunomia-bpf/eunomia.dev#32]
The [wasm-bpf.md](https://github.com/eunomia-bpf/eunomia.dev/blob/main/docs/blogs/wasm-bpf.md) file contains several broken image links, making the article less useful that it otherwise could be.

**Comment by WoodHolz** [comment]
Hey! It’s fixed. Please merge.  :-)

**Comment by yunwei37** [comment]
Thanks!
